### PR TITLE
[RFC] Default pagination settings in composables 

### PR DESCRIPTION
**Pull request by Qrzy**
[see rendered](https://github.com/DivanteLtd/next/blob/634478a3d8832633c813a303ea1af3fa9a56874c/packages/core/rfcs/20200330-pagination-default-settings.md)

### CODE REVIEW

**Comment by filrak** [comment]
I don't think we need `loadDefaultPaginationSettings` at all. Imho the defaults should be in API Client and if we will override them in search then they are overrided, that's all.

**Review by filrak — CHANGES_REQUESTED** [review]
I don't think we need loadDefaultPaginationSettings at all. Imho the defaults should be in API Client and if we will override them in search then they are overrided, that's all. Also it should be configured in API Client, not compostables - otherwise how you will handle pagination with API Client itself?

**Comment by Qrzy** [comment]
@filrak and what about the case when platform gives possibility to change the default page size on backend? Should we not reflect that immediately?

**Comment by filrak** [comment]
It should be handled on API Client level, directly in getSth method. Pagination is a parameter of search, there is no point in making a separate feature out of it when it isn't a separate feature

**Comment by filrak** [comment]
as discussed - closing

**Pull request closed without merging**
