### PR TITLE
#187 My account validation

### PR DESCRIPTION
**Pull request by defudef**
What left:
- [x] adapt messed UI because of validation

### CODE REVIEW

**Comment by filrak** [comment]
Can you include screenshots of the UI ?

**Comment by defudef** [comment]
Screenshots after UI changes:
Screenshot from 2020-03-04 16-33-18
Screenshot from 2020-03-04 16-33-22
Screenshot from 2020-03-04 16-33-32
Screenshot from 2020-03-04 16-33-52

FYI: @filrak

**Comment by defudef** [comment]
And some with validation errors

Screenshot from 2020-03-04 16-35-38
Screenshot from 2020-03-04 16-35-50

**Comment by patzick** [comment]
related #187

**Review by filrak — APPROVED** [review]

**Pull request merged**
